version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: hospital_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: hospital
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./hospital_init.sql:/docker-entrypoint-initdb.d/hospital_init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d hospital" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
